spring:
  application:
    name: lol
  datasource:
    url: jdbc:mysql://localhost:3306/lol_new?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath:/src/main/resources/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
