package com.example.lol.pojo;

import com.baomidou.mybatisplus.annotation.TableName;

import lombok.Data;

@Data
@TableName("player_vs")
public class PlayerVS {
    private String Team1_name;
    private String Team1_region;
    private String Team2_name;
    private String Team2_region;
    private String matchType;
    private int matches_played;
    private double minutes_played;
    private String Team1_player1_name;
    private String Team1_player1_position;
    private int Team1_player1_kills;
    private int Team1_player1_deaths;
    private int Team1_player1_assists;
    private int Team1_player1_CS;
    private int Team1_player1_gold;
    private double Team1_player1_damage;
    private double Team1_player1_tanking;
    private String Team1_player2_name;
    private String Team1_player2_position;
    private int Team1_player2_kills;
    private int Team1_player2_deaths;
    private int Team1_player2_assists;
    private int Team1_player2_CS;
    private int Team1_player2_gold;
    private double Team1_player2_damage;
    private double Team1_player2_tanking;
    private String Team1_player3_name;
    private String Team1_player3_position;
    private int Team1_player3_kills;
    private int Team1_player3_deaths;
    private int Team1_player3_assists;
    private int Team1_player3_CS;
    private int Team1_player3_gold;
    private double Team1_player3_damage;
    private double Team1_player3_tanking;
    private String Team1_player4_name;
    private String Team1_player4_position;
    private int Team1_player4_kills;
    private int Team1_player4_deaths;
    private int Team1_player4_assists;
    private int Team1_player4_CS;
    private int Team1_player4_gold;
    private double Team1_player4_damage;
    private double Team1_player4_tanking;
    private String Team1_player5_name;
    private String Team1_player5_position;
    private int Team1_player5_kills;
    private int Team1_player5_deaths;
    private int Team1_player5_assists;
    private int Team1_player5_CS;
    private int Team1_player5_gold;
    private double Team1_player5_damage;
    private double Team1_player5_tanking;
    private String Team2_player1_name;
    private String Team2_player1_position;
    private int Team2_player1_kills;
    private int Team2_player1_deaths;
    private int Team2_player1_assists;
    private int Team2_player1_CS;
    private int Team2_player1_gold;
    private double Team2_player1_damage;
    private double Team2_player1_tanking;
    private String Team2_player2_name;
    private String Team2_player2_position;
    private int Team2_player2_kills;
    private int Team2_player2_deaths;
    private int Team2_player2_assists;
    private int Team2_player2_CS;
    private int Team2_player2_gold;
    private double Team2_player2_damage;
    private double Team2_player2_tanking;
    private String Team2_player3_name;
    private String Team2_player3_position;
    private int Team2_player3_kills;
    private int Team2_player3_deaths;
    private int Team2_player3_assists;
    private int Team2_player3_CS;
    private int Team2_player3_gold;
    private double Team2_player3_damage;
    private double Team2_player3_tanking;
    private String Team2_player4_name;
    private String Team2_player4_position;
    private int Team2_player4_kills;
    private int Team2_player4_deaths;
    private int Team2_player4_assists;
    private int Team2_player4_CS;
    private int Team2_player4_gold;
    private double Team2_player4_damage;
    private double Team2_player4_tanking;
    private String Team2_player5_name;
    private String Team2_player5_position;
    private int Team2_player5_kills;
    private int Team2_player5_deaths;
    private int Team2_player5_assists;
    private int Team2_player5_CS;
    private int Team2_player5_gold;
    private double Team2_player5_damage;
    private double Team2_player5_tanking;

}
